# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ruby.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(491, 832)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hanzi_groupbox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hanzi_groupbox.sizePolicy().hasHeightForWidth())
        self.hanzi_groupbox.setSizePolicy(sizePolicy)
        self.hanzi_groupbox.setMouseTracking(False)
        self.hanzi_groupbox.setFlat(False)
        self.hanzi_groupbox.setObjectName("hanzi_groupbox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.hanzi_groupbox)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setContentsMargins(12, -1, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.hanzi_groupbox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.deck_combobox = QtWidgets.QComboBox(self.hanzi_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deck_combobox.sizePolicy().hasHeightForWidth())
        self.deck_combobox.setSizePolicy(sizePolicy)
        self.deck_combobox.setStyleSheet("")
        self.deck_combobox.setObjectName("deck_combobox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deck_combobox)
        self.label_2 = QtWidgets.QLabel(self.hanzi_groupbox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.note_combobox = QtWidgets.QComboBox(self.hanzi_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.note_combobox.sizePolicy().hasHeightForWidth())
        self.note_combobox.setSizePolicy(sizePolicy)
        self.note_combobox.setObjectName("note_combobox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.note_combobox)
        self.label_3 = QtWidgets.QLabel(self.hanzi_groupbox)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.field_combobox = QtWidgets.QComboBox(self.hanzi_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_combobox.sizePolicy().hasHeightForWidth())
        self.field_combobox.setSizePolicy(sizePolicy)
        self.field_combobox.setObjectName("field_combobox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.field_combobox)
        self.verticalLayout_2.addWidget(self.hanzi_groupbox)
        self.pinyin_groupbox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pinyin_groupbox.sizePolicy().hasHeightForWidth())
        self.pinyin_groupbox.setSizePolicy(sizePolicy)
        self.pinyin_groupbox.setFlat(False)
        self.pinyin_groupbox.setObjectName("pinyin_groupbox")
        self.formLayout = QtWidgets.QFormLayout(self.pinyin_groupbox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_pinyin_setting = QtWidgets.QLabel(self.pinyin_groupbox)
        self.label_pinyin_setting.setObjectName("label_pinyin_setting")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_pinyin_setting)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radio_match_strict = QtWidgets.QRadioButton(self.pinyin_groupbox)
        self.radio_match_strict.setObjectName("radio_match_strict")
        self.pinyin_option = QtWidgets.QButtonGroup(Dialog)
        self.pinyin_option.setObjectName("pinyin_option")
        self.pinyin_option.addButton(self.radio_match_strict)
        self.verticalLayout.addWidget(self.radio_match_strict)
        self.radio_match_fallback = QtWidgets.QRadioButton(self.pinyin_groupbox)
        self.radio_match_fallback.setObjectName("radio_match_fallback")
        self.pinyin_option.addButton(self.radio_match_fallback)
        self.verticalLayout.addWidget(self.radio_match_fallback)
        self.radio_generate = QtWidgets.QRadioButton(self.pinyin_groupbox)
        self.radio_generate.setObjectName("radio_generate")
        self.pinyin_option.addButton(self.radio_generate)
        self.verticalLayout.addWidget(self.radio_generate)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.pinyin_match_label = QtWidgets.QLabel(self.pinyin_groupbox)
        self.pinyin_match_label.setObjectName("pinyin_match_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pinyin_match_label)
        self.pinyin_match_combobox = QtWidgets.QComboBox(self.pinyin_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pinyin_match_combobox.sizePolicy().hasHeightForWidth())
        self.pinyin_match_combobox.setSizePolicy(sizePolicy)
        self.pinyin_match_combobox.setObjectName("pinyin_match_combobox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pinyin_match_combobox)
        self.pinyin_generate_combobox = QtWidgets.QComboBox(self.pinyin_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pinyin_generate_combobox.sizePolicy().hasHeightForWidth())
        self.pinyin_generate_combobox.setSizePolicy(sizePolicy)
        self.pinyin_generate_combobox.setObjectName("pinyin_generate_combobox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pinyin_generate_combobox)
        self.pinyin_generate_label = QtWidgets.QLabel(self.pinyin_groupbox)
        self.pinyin_generate_label.setObjectName("pinyin_generate_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pinyin_generate_label)
        self.label_4 = QtWidgets.QLabel(self.pinyin_groupbox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.ruby_combobox = QtWidgets.QComboBox(self.pinyin_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ruby_combobox.sizePolicy().hasHeightForWidth())
        self.ruby_combobox.setSizePolicy(sizePolicy)
        self.ruby_combobox.setObjectName("ruby_combobox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ruby_combobox)
        self.verticalLayout_2.addWidget(self.pinyin_groupbox)
        self.cedict_groupbox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cedict_groupbox.sizePolicy().hasHeightForWidth())
        self.cedict_groupbox.setSizePolicy(sizePolicy)
        self.cedict_groupbox.setObjectName("cedict_groupbox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.cedict_groupbox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.cedict_groupbox)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.cedict_checkbox = QtWidgets.QCheckBox(self.cedict_groupbox)
        self.cedict_checkbox.setObjectName("cedict_checkbox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cedict_checkbox)
        self.cedict_label = QtWidgets.QLabel(self.cedict_groupbox)
        self.cedict_label.setObjectName("cedict_label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cedict_label)
        self.cedict_combobox = QtWidgets.QComboBox(self.cedict_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cedict_combobox.sizePolicy().hasHeightForWidth())
        self.cedict_combobox.setSizePolicy(sizePolicy)
        self.cedict_combobox.setObjectName("cedict_combobox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cedict_combobox)
        self.verticalLayout_2.addWidget(self.cedict_groupbox)
        self.widget_match = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_match.sizePolicy().hasHeightForWidth())
        self.widget_match.setSizePolicy(sizePolicy)
        self.widget_match.setObjectName("widget_match")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_match)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.count_label_match = QtWidgets.QLabel(self.widget_match)
        self.count_label_match.setObjectName("count_label_match")
        self.verticalLayout_4.addWidget(self.count_label_match)
        self.preview_match_layout = QtWidgets.QHBoxLayout()
        self.preview_match_layout.setObjectName("preview_match_layout")
        self.list_match = QtWidgets.QListWidget(self.widget_match)
        self.list_match.setObjectName("list_match")
        self.preview_match_layout.addWidget(self.list_match)
        self.label_6 = QtWidgets.QLabel(self.widget_match)
        self.label_6.setObjectName("label_6")
        self.preview_match_layout.addWidget(self.label_6)
        self.verticalLayout_4.addLayout(self.preview_match_layout)
        self.button_match = QtWidgets.QPushButton(self.widget_match)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_match.sizePolicy().hasHeightForWidth())
        self.button_match.setSizePolicy(sizePolicy)
        self.button_match.setObjectName("button_match")
        self.verticalLayout_4.addWidget(self.button_match)
        self.verticalLayout_2.addWidget(self.widget_match)
        self.widget_generate = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_generate.sizePolicy().hasHeightForWidth())
        self.widget_generate.setSizePolicy(sizePolicy)
        self.widget_generate.setObjectName("widget_generate")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_generate)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.count_label_generate = QtWidgets.QLabel(self.widget_generate)
        self.count_label_generate.setObjectName("count_label_generate")
        self.verticalLayout_3.addWidget(self.count_label_generate)
        self.preview_generate_layout = QtWidgets.QHBoxLayout()
        self.preview_generate_layout.setObjectName("preview_generate_layout")
        self.list_generate = QtWidgets.QListWidget(self.widget_generate)
        self.list_generate.setObjectName("list_generate")
        self.preview_generate_layout.addWidget(self.list_generate)
        self.label_7 = QtWidgets.QLabel(self.widget_generate)
        self.label_7.setObjectName("label_7")
        self.preview_generate_layout.addWidget(self.label_7)
        self.verticalLayout_3.addLayout(self.preview_generate_layout)
        self.button_generate = QtWidgets.QPushButton(self.widget_generate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_generate.sizePolicy().hasHeightForWidth())
        self.button_generate.setSizePolicy(sizePolicy)
        self.button_generate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_generate.setObjectName("button_generate")
        self.verticalLayout_3.addWidget(self.button_generate)
        self.verticalLayout_2.addWidget(self.widget_generate)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.hanzi_groupbox.setTitle(_translate("Dialog", "Hanzi selection"))
        self.label.setText(_translate("Dialog", "Deck"))
        self.label_2.setText(_translate("Dialog", "Note type"))
        self.label_3.setText(_translate("Dialog", "Field"))
        self.pinyin_groupbox.setTitle(_translate("Dialog", "Pinyin"))
        self.label_pinyin_setting.setText(_translate("Dialog", "Option"))
        self.radio_match_strict.setText(_translate("Dialog", "Pinyin already exists, ignore empty pinyin"))
        self.radio_match_fallback.setText(_translate("Dialog", "Pinyin already exists, but generate where empty"))
        self.radio_generate.setText(_translate("Dialog", "Generate for all cards, replacing already existing pinyin"))
        self.pinyin_match_label.setText(_translate("Dialog", "Find pinyin in"))
        self.pinyin_generate_label.setText(_translate("Dialog", "Pinyin output"))
        self.label_4.setText(_translate("Dialog", "Ruby output"))
        self.cedict_groupbox.setTitle(_translate("Dialog", "CEDICT dictionary entries"))
        self.label_9.setText(_translate("Dialog", "Option"))
        self.cedict_checkbox.setText(_translate("Dialog", "Construct a table of definitions for each word"))
        self.cedict_label.setText(_translate("Dialog", "Output"))
        self.widget_match.setTitle(_translate("Dialog", "Existing pinyin"))
        self.count_label_match.setText(_translate("Dialog", "Found # notes with matching pinyin."))
        self.label_6.setText(_translate("Dialog", "→"))
        self.button_match.setText(_translate("Dialog", "Add ruby"))
        self.widget_generate.setTitle(_translate("Dialog", "Pinyin to generate"))
        self.count_label_generate.setText(_translate("Dialog", "Found # notes with empty or unusual pinyin"))
        self.label_7.setText(_translate("Dialog", "→"))
        self.button_generate.setText(_translate("Dialog", "Add ruby"))

